### ISSUE TITLE
Add dark mode support

### ISSUE THREAD

**Issue by alazymeme** [pajbot/pajbot#653]

**Comment by alazymeme** [comment]
@pajlada What are your thoughts on using the dark reader api for this? https://github.com/darkreader/darkreader

It can sync to whether you are using dark/light mode on windows (which is a nice feature)

**Comment by RAnders00** [comment]
Just wanted to point out this is a feature that stems from CSS, and therefore can of course also be directly used in the CSS of the website:

```css
.something {
    background: white;
    color: black;
}

@media (prefers-color-scheme: dark) {
    .something {
        background: black;
        color: white;
    }
}
```

https://css-tricks.com/dark-modes-with-css/
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
